###취미 게시판 전체 보기
GET http://localhost:8081/hobby-board

###취미 게시판 카테고리별 전체보기
GET http://localhost:8081/hobby-board/1

###취미 게시판 상세 보기, 관련된 후기 가져오기
GET http://localhost:8081/hobby-detail/1

###취미 게시판 후기 작성
POST http://localhost:8081/1/hobby-review
Content-Type: application/json;charset=UTF-8

{
  "hobbyReviewRate": 4,
  "hobbyReviewDetail": "좋아요!",
  "hobbyReviewHealthStatus": 1,
  "hobbyReviewTendency": 1,
  "hobbyReviewLevel": 3,
  "hobbyReviewWriteDate": "2024-12-02"
}

###취미 게시판 후기 수정
POST http://localhost:8081/1/hobby-review/1

###취미 게시판 후기 삭제
DELETE http://localhost:8081/1/hobby-review/8

