### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 모임 검색
GET http://localhost:8080/partyboards/search

###
GET http://localhost:8080/partyboards/search?cursor=3&isAscending=1

###
GET http://localhost:8080/partyboards/search?cursor=7&isAscending=1&sortMethod=mostLiked

###
GET http://localhost:8080/partyboards/search?cursor=3&isAscending=1


### 모임 상세 조회
GET http://localhost:8080/partyboards/test

### 모임 글 작성
POST http://localhost:8080/partyboards

### 모임 글 수정
PUT http://localhost:8080/partyboards/1

### 모임 글 삭제
DELETE http://localhost:8080/partyboards
Content-Type: application/json

{
  "partyBoardNumber": 16
}

### 모임 내 일정 전체 조회
GET http://localhost:8080/partyboards/1/meets

### 모임 일정 추가
POST http://localhost:8080/partyboards/2/meets
Content-Type: application/json;charset=UTF-8

{
    "partyBoardNumber": 2,
    "meetStartDate": "2024-12-30",
    "meetEndDate": "2025-01-10",
    "meetStartTime": "12:00",
    "meetFinishTime": "14:00",
    "meetEntryFee": 5000,
    "meetLocation": "testLocation",
    "meetMaxMember": 123
}

### 모임 일정 수정
PUT http://localhost:8080/partyboards/2/meets/6
Content-Type: application/json;charset=UTF-8

{
  "meetStartDate": "2024-12-31",
  "meetEndDate": "2025-01-11",
  "meetStartTime": "12:01",
  "meetFinishTime": "14:01",
  "meetEntryFee": 5001,
  "meetLocation": "testLocation변경1",
  "meetMaxMember": 111
}

### 모임 일정 삭제
DELETE http://localhost:8080/partyboards/2/meets/6

### 모임 일정 참여멤버 조회
GET http://localhost:8080/partyboards/1/meets/1/meetmembers

### 모임 후기 전체 조회
GET http://localhost:8080/partyboards/1/partyreviews


### 모임 후기 작성
POST http://localhost:8080/partyboards/1/partyreviews
Content-Type: application/json;application/json;charset=UTF-8

{
  "partyReviewRate" : 3,
  "partyReviewDetail" : "testPartyReviewDetail"
}

### 모임 후기 수정
PUT http://localhost:8080/partyboards/1/partyreviews/10
Content-Type: application/json;application/json;charset=UTF-8

{
  "partyReviewRate" : 4,
  "partyReviewDetail" : "testPartyReviewDetailModified"
}

### 모임 후기 삭제
DELETE http://localhost:8080/partyboards/1/partyreviews/10

### 모임 멤버 전체 조회
GET /partyboards/{partyBoardNumber}/partymembers

### 모임 탈퇴
DELETE /partyboards/{partyBoardNumber}/partymembers/{partyMemberNumber}
